# This is a config where there are
# 2 leaders, 4 followers per leader for a total of 8 followers
# 4 POI with a coupling of 4
# Leader must learn to get its followers to the POI
# The followers are positioned around the corner agent sensors of each leader
CCEA:
  config:
    BoidsEnv:
      config:
        BoidSpawner:
          spawn_rule: Individual
          position_rule: Set
          velocity_rule: FixedStart
          heading_rule: FixedStart
          velocity_fraction: 0.0
          start_heading: !eval 3.14159/2
          leader_positions: # 2 leaders
            - [20,20]
            - [40,20]
          follower_positions: # 8 followers
          # 4 followers for the first leader
            - [21.8, 21.8]
            - [21.8, 18.2]
            - [18.2, 18.2]
            - [18.2, 21.8]
          # 4 followers for the second leader
            - [38.2, 21.8]
            - [41.8, 21.8]
            - [41.8, 18.2]
            - [38.2, 18.2]
        BoidsColony:
          dt: !eval 1/5
          radius_attraction: !eval 5
          radius_orientation: !eval 3
          radius_repulsion: !eval   2
          attraction_multiplier: 1
          orientation_multiplier: 1
          repulsion_multiplier: 1
          wall_avoidance_multiplier: 0
        ObservationManager:
          num_poi_bins: 4
          num_swarm_bins: 4
          observation_rule: Individual
          poi_sensor_type: Density
          swarm_sensor_type: Density
          observation_radius: ~
          full_observability: true
        POIColony:
          coupling: 4
          observation_radius: 1000
        FitnessCalculator:
          which_G: ContinuousObsRadLastStep
          which_D: DFollow
        POISpawner:
          positions:
            - [20, 40]
            - [40, 40]
          poi_spawn_rule: Set
        Renderer:
          leader_colors:
          - - 250
            - 120
            - 0
          - - 120
            - 0
            - 250
          - - 250
            - 250
            - 0
          - - 0
            - 200
            - 0
          - - 120
            - 0
            - 120
          - - 66
            - 245
            - 242
          pixels_per_unit: 10
        StateBounds:
          max_acceleration: 5
          max_angular_velocity: 1.570795
          max_velocity: 10
          min_velocity: 0
          num_followers: 8
          num_leaders: 2
        map_dimensions:
          x: 100
          y: 100
      init_seed: 1
      max_steps: !eval 5*10
      render_mode: none
  mutation_probability: 0.5
  mutation_rate: 0.1
  nn_hidden:
  - 10
  - 10
  num_evaluations: 1
  num_workers: 19
  sub_population_size: 50
load_population: null
num_generations: 1
