# This is a config where there are
# 5 leaders, 5 followers, 25 pois
# This is interesting because we can have one follower cover several pois
# But it's not clear where to put the followers or how to interact with them to get them 
# where they need to be
CCEA:
  config:
    BoidsEnv:
      config:
        BoidSpawner:
          spawn_rule: Individual
          position_rule: Set
          velocity_rule: FixedStart
          heading_rule: FixedStart
          velocity_fraction: 0.0
          start_heading: !eval 3.14159/2
          leader_positions: # 5 leaders
          - [ 10, 10.0 ]
          - [ 20, 10.0 ]
          - [ 30, 10.0 ]
          - [ 40, 10.0 ]
          - [ 50, 10.0 ]
          follower_positions: # 5 followers. One per leader
          - [ 10, 20.0 ]
          - [ 20, 20.0 ]
          - [ 30, 20.0 ]
          - [ 40, 20.0 ]
          - [ 50, 20.0 ]
        BoidsColony:
          dt: !eval 1/5
          radius_attraction: !eval 5
          radius_orientation: !eval 3
          radius_repulsion: !eval   2
          attraction_multiplier: 2
          orientation_multiplier: 2
          repulsion_multiplier: 2
          wall_avoidance_multiplier: 1
        ObservationManager:
          num_poi_bins: 4
          num_swarm_bins: 4
          observation_rule: Individual
          poi_sensor_type: Density
          swarm_sensor_type: Density
          observation_radius: ~
          full_observability: true
        POIColony:
          coupling: 1
          observation_radius: 1000
        FitnessCalculator:
          which_G: ContinuousObsRadLastStep
          which_D: DFollow
          follower_switch: UseFollowersOnly
        POISpawner:
          positions:
          - [ 30.85570096133541 ,53.04947844164283 ]
          - [ 17.15927232524152 ,80.21127948659446 ]
          - [ 50.749966414088966 ,50.62175871884587 ]
          - [ 19.970966288697426 ,63.430827520581374 ]
          - [ 49.15370349249811 ,76.68729805185154 ]
          - [ 19.396999736268526 ,71.82010103424827 ]
          - [ 16.982809863936353 ,74.68571192117057 ]
          - [ 28.840796382638107 ,56.165907256164076 ]
          - [ 22.067383231960182 ,32.152235448540935 ]
          - [ 18.2947521288453 ,45.433429195185326 ]
          - [ 6.980383102208327 ,84.97080105165543 ]
          - [ 12.537688449098928 ,65.52231561223519 ]
          - [ 21.098995866635597 ,61.13443415261602 ]
          - [ 39.21813109730088 ,80.37484891621679 ]
          - [ 51.04314042527751 ,50.90531201728841 ]
          - [ 49.811105773497765 ,61.62752383140113 ]
          - [ 7.9933570505422 ,35.33930928563039 ]
          - [ 16.14479110122339 ,73.03289585811402 ]
          - [ 29.70167682088294 ,55.90457664085261 ]
          - [ 16.923304030048843 ,65.99851695853962 ]
          - [ 45.88909038809518 ,92.84074188961235 ]
          - [ 35.97640861430002 ,80.17337807213381 ]
          - [ 27.85016910214024 ,78.89928166361591 ]
          - [ 23.647741450311244 ,89.67439738025097 ]
          - [ 21.5430813150111 ,37.06961690324804 ]
          poi_spawn_rule: Set
        Renderer:
          leader_colors:
          - - 250
            - 120
            - 0
          - - 120
            - 0
            - 250
          - - 250
            - 250
            - 0
          - - 0
            - 200
            - 0
          - - 120
            - 0
            - 120
          - - 66
            - 245
            - 242
          pixels_per_unit: 10
        StateBounds:
          max_acceleration: 5
          max_angular_velocity: 1.570795
          max_velocity: 10
          min_velocity: 0
          num_followers: 5
          num_leaders: 5
        map_dimensions:
          x: 60
          y: 100
      init_seed: 1
      max_steps: !eval 5*10
      render_mode: none
  mutation_probability: 0.5
  mutation_rate: 0.1
  nn_hidden:
  - 10
  - 10
  num_evaluations: 1
  num_workers: 19
  sub_population_size: 50
load_population: null
num_generations: 1
