# This is a config where there are
# 5 leaders, followers, pois
# Leaders must just learn to drive straight to get their follower to their poi
# Not much room for leaders to interact with each other or trade followers or anything like that
CCEA:
  config:
    BoidsEnv:
      config:
        BoidSpawner:
          spawn_rule: Individual
          position_rule: Set
          velocity_rule: FixedStart
          heading_rule: FixedStart
          velocity_fraction: 0.0
          start_heading: !eval 3.14159/2
          leader_positions: # 5 leaders
          - [ 30, 10.0 ]
          - [ 60, 10.0 ]
          - [ 90, 10.0 ]
          - [ 120, 10.0 ]
          - [ 150, 10.0 ]
          follower_positions: # 5 followers. One per leader
          - [ 30, 7.5 ]
          - [ 60, 7.5 ]
          - [ 90, 7.5 ]
          - [ 120, 7.5 ]
          - [ 150, 7.5 ]
        BoidsColony:
          dt: !eval 1/5
          radius_attraction: !eval 5
          radius_orientation: !eval 3
          radius_repulsion: !eval   2
          attraction_multiplier: 1
          orientation_multiplier: 1
          repulsion_multiplier: 1
          wall_avoidance_multiplier: 0
        ObservationManager:
          num_poi_bins: 4
          num_swarm_bins: 4
          observation_rule: Individual
          poi_sensor_type: Density
          swarm_sensor_type: Density
          observation_radius: ~
          full_observability: true
        POIColony:
          coupling: 1
          observation_radius: 1000
        FitnessCalculator:
          which_G: ContinuousObsRadLastStep
          which_D: DFollow
          follower_switch: UseFollowersOnly
        POISpawner:
          positions:
          - [ 30, 25.0 ]
          - [ 60, 25.0 ]
          - [ 90, 25.0 ]
          - [ 120, 25.0 ]
          - [ 150, 25.0 ]
          poi_spawn_rule: Set
        Renderer:
          leader_colors:
          - - 250
            - 120
            - 0
          - - 120
            - 0
            - 250
          - - 250
            - 250
            - 0
          - - 0
            - 200
            - 0
          - - 120
            - 0
            - 120
          - - 66
            - 245
            - 242
          pixels_per_unit: 10
        StateBounds:
          max_acceleration: 5
          max_angular_velocity: 1.570795
          max_velocity: 10
          min_velocity: 0
          num_followers: 5
          num_leaders: 5
        map_dimensions:
          x: 150
          y: 150
      init_seed: 1
      max_steps: !eval 5*10
      render_mode: none
  mutation_probability: 0.5
  mutation_rate: 0.1
  nn_hidden:
  - 10
  - 10
  num_evaluations: 1
  num_workers: 19
  sub_population_size: 50
load_population: null
num_generations: 1
