leader_positions:
  - [ 10, 5 ]
  - [ 20, 5 ]
  - [ 30, 5 ]
  - [ 40, 5 ]
follower_positions:
  - [ 8, 2 ]
  - [ 12, 2 ]
  #
  - [ 18, 2 ]
  - [ 22, 2 ]
  #
  - [ 28, 2 ]
  - [ 32, 2 ]
  #
  - [ 38, 2 ]
  - [ 42, 2 ]
poi_positions:
  - [ 10, 15 ]
  - [ 20, 15 ]
  - [ 30, 15 ]
  - [ 40, 15 ]
