leader_positions:
  - [2, 13]
  - [3, 13]
follower_positions:
  - [1.5, 12.5]
  - [1.5, 13.5]
  - [2.5, 12.5]
  - [2.5, 13.5]
  - [3.5, 12.5]
  - [3.5, 13.5]
poi_positions:
  - [1, 9]
  - [2, 8]
  - [2, 3]
  - [6, 3]
  - [10, 3]
  - [9, 8]
  - [8, 8]
  - [9, 9]
  - [10, 14]
  - [7, 13]
