leader_positions:
  - [ 10, 5 ]
  - [ 20, 5 ]
  - [ 30, 5 ]
  - [ 40, 5 ]
follower_positions:
  - [ 8, 2 ]
  - [ 8,  7 ]
  - [ 12, 2 ]
  - [ 12, 7 ]
  #
  - [ 18, 2 ]
  - [ 18, 7 ]
  - [ 22, 2 ]
  - [ 22, 7 ]
  #
  - [ 28, 2 ]
  - [ 28, 7 ]
  - [ 32, 2 ]
  - [ 32, 7 ]
  #
  - [ 38, 2 ]
  - [ 38, 7 ]
  - [ 42, 2 ]
  - [ 42, 7 ]
poi_positions:
  - [ 10, 30 ]
  - [ 20, 30 ]
  - [ 30, 30 ]
  - [ 40, 30 ]