CCEA:
  config:
    BoidsEnv:
      config:
        BoidSpawner:
          fix_all: false
          radius_fraction: 0.02
          spawn_rule: Circle
          velocity_fraction: 0
        BoidsColony:
          attraction_multiplier: 1
          dt: 0.333333
          orientation_multiplier: 1
          radius_attraction: 5
          radius_orientation: 3
          radius_repulsion: 2
          repulsion_multiplier: 3
          wall_avoidance_multiplier: 1
        ObservationManager:
          num_poi_bins: 4
          num_swarm_bins: 4
          observation_rule: Individual
          poi_sensor_type: InverseDistance
          swarm_sensor_type: InverseDistance
        POIColony:
          coupling: 1
          observation_radius: 5
        POISpawner:
          bound_fraction: 0.5
          concentric_radii_fraction:
          - 0.428571
          fix_poi_spawns: false
          inner_circle_bound_fraction: 0.2
          num_pois: null
          num_pois_concentric:
          - 13
          outer_circle_bound_fraction: 0.4
          poi_spawn_rule: FixedConcentricCircles
        Renderer:
          pixels_per_unit: 20
        StateBounds:
          max_acceleration: 10
          max_angular_velocity: 1.570795
          max_velocity: 20
          min_velocity: 0
          num_followers: 0
          num_leaders: 3
        map_dimensions:
          x: 50
          y: 50
      max_steps: 30
      render_mode: none
  mutation_probability: 0.15
  mutation_rate: 0.15
  nn_hidden:
  - 10
  num_evaluations: 10
  num_parents: 5
  num_workers: 8
  sub_population_size: 15
  use_difference_evaluations: true
Notes: 0 followers. 1 leader. 1 coupling.
load_population: null
num_generations: 500
