CCEA:
  config:
    BoidsEnv:
      config:
        BoidSpawner:
          follower_positions:
          - - 10
            - 10
          - - 30
            - 30
          - - 30
            - 10
          - - 10
            - 30
          heading_rule: FixedStart
          leader_positions:
          - - 20
            - 20
          position_rule: Set
          spawn_rule: Individual
          start_heading: 1.570795
          velocity_fraction: 0.0
          velocity_rule: FixedStart
        BoidsColony:
          attraction_multiplier: 2
          dt: 0.2
          orientation_multiplier: 2
          radius_attraction: 10
          radius_orientation: 6
          radius_repulsion: 4
          repulsion_multiplier: 2
          wall_avoidance_multiplier: 1
        FitnessCalculator:
          which_D: G
          which_G: ContinuousObsRadLastStep
        ObservationManager:
          full_observability: true
          num_poi_bins: 4
          num_swarm_bins: 4
          observation_radius: null
          observation_rule: Individual
          poi_sensor_type: Density
          swarm_sensor_type: Density
        POIColony:
          coupling: 3
          observation_radius: 1000
        POISpawner:
          poi_spawn_rule: Set
          positions:
          - - 20.1
            - 20.1
        Renderer:
          leader_colors:
          - - 250
            - 120
            - 0
          - - 120
            - 0
            - 250
          - - 250
            - 250
            - 0
          - - 0
            - 200
            - 0
          - - 120
            - 0
            - 120
          - - 66
            - 245
            - 242
          pixels_per_unit: 7
        StateBounds:
          max_acceleration: 5
          max_angular_velocity: 1.570795
          max_velocity: 10
          min_velocity: 0
          num_followers: 4
          num_leaders: 1
        map_dimensions:
          x: 100
          y: 150
      init_seed: 1
      max_steps: 50
      render_mode: none
  mutation_probability: 0.15
  mutation_rate: 0.1
  nn_hidden:
  - 9
  num_evaluations: 1
  num_workers: 19
  sub_population_size: 15
load_population: null
num_generations: 100
