CCEA:
  config:
    BoidsEnv:
      config:
        BoidSpawner:
          heading_rule: FixedStart
          leader_positions:
          - - 25
            - 15
          position_rule: Set
          spawn_rule: Individual
          start_heading: 1.570795
          velocity_fraction: 0.0
          velocity_rule: FixedStart
        BoidsColony:
          attraction_multiplier: 0.2
          dt: 0.2
          orientation_multiplier: 0.2
          radius_attraction: 5
          radius_orientation: 3
          radius_repulsion: 2
          repulsion_multiplier: 0.6
          wall_avoidance_multiplier: 0.6
        ObservationManager:
          num_poi_bins: 4
          num_swarm_bins: 4
          observation_radius: 5
          observation_rule: Individual
          poi_sensor_type: InverseDistanceCentroid
          swarm_sensor_type: InverseDistanceCentroid
        POIColony:
          coupling: 1
          observation_radius: 5
        POISpawner:
          poi_spawn_rule: Set
          positions:
          - - 25
            - 25
        Renderer:
          leader_colors:
          - - 250
            - 120
            - 0
          - - 120
            - 0
            - 250
          - - 250
            - 250
            - 0
          - - 0
            - 200
            - 0
          - - 120
            - 0
            - 120
          - - 66
            - 245
            - 242
          pixels_per_unit: 10
        StateBounds:
          max_acceleration: 5
          max_angular_velocity: 1.570795
          max_velocity: 10
          min_velocity: 0
          num_followers: 0
          num_leaders: 1
        map_dimensions:
          x: 50
          y: 50
      init_seed: 11
      max_steps: 25
      render_mode: none
  mutation_probability: 0.15
  mutation_rate: 0.1
  nn_hidden:
  - 10
  num_evaluations: 1
  num_workers: 2
  sub_population_size: 30
  use_difference_evaluations: true
load_population: null
num_generations: 3
