CCEA:
  config:
    BoidsEnv:
      config:
        BoidSpawner:
          follower_positions:
          - - 55
            - 25
          - - 55
            - 30
          - - 55
            - 35
          - - 55
            - 40
          - - 55
            - 45
          - - 55
            - 50
          - - 55
            - 55
          - - 55
            - 60
          - - 55
            - 65
          - - 55
            - 70
          - - 55
            - 75
          - - 55
            - 80
          - - 55
            - 85
          - - 55
            - 90
          - - 55
            - 95
          - - 55
            - 100
          - - 55
            - 105
          - - 55
            - 110
          - - 55
            - 115
          - - 55
            - 120
          heading_rule: FixedStart
          leader_positions:
          - - 50
            - 25
          - - 50
            - 30
          - - 50
            - 35
          - - 50
            - 40
          - - 50
            - 45
          - - 50
            - 50
          - - 50
            - 55
          - - 50
            - 60
          - - 50
            - 65
          - - 50
            - 70
          - - 50
            - 75
          - - 50
            - 80
          - - 50
            - 85
          - - 50
            - 90
          - - 50
            - 95
          - - 50
            - 100
          - - 50
            - 105
          - - 50
            - 110
          - - 50
            - 115
          - - 50
            - 120
          position_rule: Set
          spawn_rule: Individual
          start_heading: 1.570795
          velocity_fraction: 0.0
          velocity_rule: FixedStart
        BoidsColony:
          attraction_multiplier: 2
          dt: 0.2
          orientation_multiplier: 2
          radius_attraction: 10
          radius_orientation: 6
          radius_repulsion: 4
          repulsion_multiplier: 2
          wall_avoidance_multiplier: 1
        FitnessCalculator:
          which_D: DFollow
          which_G: ContinuousObsRadLastStep
        ObservationManager:
          full_observability: true
          num_poi_bins: 4
          num_swarm_bins: 4
          observation_radius: null
          observation_rule: Individual
          poi_sensor_type: Density
          swarm_sensor_type: Density
        POIColony:
          coupling: 6
          observation_radius: 1000
        POISpawner:
          poi_spawn_rule: Set
          positions:
          - - 25
            - 25
          - - 25
            - 30
          - - 25
            - 35
          - - 25
            - 40
          - - 25
            - 45
          - - 25
            - 50
          - - 25
            - 55
          - - 25
            - 60
          - - 25
            - 65
          - - 25
            - 70
          - - 25
            - 75
          - - 25
            - 80
          - - 25
            - 85
          - - 25
            - 90
          - - 25
            - 95
          - - 25
            - 100
          - - 25
            - 105
          - - 25
            - 110
          - - 25
            - 115
          - - 25
            - 120
        Renderer:
          leader_colors:
          - - 250
            - 120
            - 0
          - - 120
            - 0
            - 250
          - - 250
            - 250
            - 0
          - - 0
            - 200
            - 0
          - - 120
            - 0
            - 120
          - - 66
            - 245
            - 242
          pixels_per_unit: 7
        StateBounds:
          max_acceleration: 5
          max_angular_velocity: 1.570795
          max_velocity: 10
          min_velocity: 0
          num_followers: 20
          num_leaders: 20
        map_dimensions:
          x: 100
          y: 150
      init_seed: 1
      max_steps: 50
      render_mode: none
  mutation_probability: 0.15
  mutation_rate: 0.1
  nn_hidden:
  - 9
  num_evaluations: 1
  num_workers: 10
  sub_population_size: 15
load_population: null
num_generations: 100
