CCEA:
  config:
    BoidsEnv:
      config:
        BoidSpawner:
          spawn_rule: Individual
          position_rule: Set
          velocity_rule: FixedStart
          heading_rule: FixedStart
          velocity_fraction: 0.0
          start_heading: !eval 3.14159
          leader_positions: # 4 leaders
            - [70, 90]
            - [70, 80]
            - [80, 80]
            - [90, 80]
          follower_positions: # 8 followers
            # First row
            - [75, 90]
            - [80, 90]
            - [85, 90]
            - [90, 90]
            # Second row
            - [75, 85]
            - [80, 85]
            - [85, 85]
            - [90, 85] 
        BoidsColony:
          dt: !eval 1/5
          radius_attraction: !eval 5
          radius_orientation: !eval 1.000000001
          radius_repulsion: !eval   1
          attraction_multiplier: 5
          orientation_multiplier: 0
          repulsion_multiplier: 1
          wall_avoidance_multiplier: 1
        ObservationManager:
          num_poi_bins: 4
          num_swarm_bins: 4
          observation_rule: Individual
          poi_sensor_type: Density
          swarm_sensor_type: Density
          observation_radius: ~
          full_observability: true
        POIColony:
          coupling: 3
          observation_radius: 5
        POISpawner:
          positions:
            # A
            - [10, 80]
            - [10, 80]
            # B
            - [20, 70]
            - [20, 70]
            - [20, 70]
            - [20, 70]
            # C
            - [10, 60]
            - [10, 60]
            - [10, 60]
            - [10, 60]
            # D
            - [5, 20]
            - [5, 20]
            - [5, 20]
            - [5, 20]
            - [5, 20]
            # E
            - [10, 15]
            # F
            - [25, 15]
            - [25, 15]
            # G
            - [30, 20]
            - [30, 20]
            - [30, 20]
            # H
            - [80, 20]
            - [80, 20]
            # I
            - [80, 30]
            # J
            - [80, 40]
          poi_spawn_rule: Set
        Renderer:
          leader_colors:
          - - 250
            - 120
            - 0
          - - 120
            - 0
            - 250
          - - 250
            - 250
            - 0
          - - 0
            - 200
            - 0
          - - 120
            - 0
            - 120
          - - 66
            - 245
            - 242
          pixels_per_unit: 10
        StateBounds:
          max_acceleration: 5
          max_angular_velocity: 1.570795
          max_velocity: 10
          min_velocity: 0
          num_followers: 8
          num_leaders: 4
        map_dimensions:
          x: 100
          y: 100
      init_seed: 1
      max_steps: !eval 5*5
      render_mode: none
  mutation_probability: 0.15
  mutation_rate: 0.1
  nn_hidden:
  - 10
  num_evaluations: 1
  num_workers: 8
  sub_population_size: 30
  use_difference_evaluations: false
load_population: null
num_generations: 20