---
num_generations: 5000
load_population: ~
CCEA:
  sub_population_size: 15
  num_parents: 5
  mutation_rate: 0.15
  mutation_probability: 0.15
  nn_hidden:
    - 10
  num_workers: 4
  use_difference_evaluations: True
  num_evaluations: 5
  config:
    BoidsEnv:
      max_steps: !eval 5*5
      render_mode: none
      config:
        map_dimensions:
          x: 100
          y: 100
        StateBounds:
          min_velocity: 0
          max_velocity: 10
          max_acceleration: 5
          max_angular_velocity: !eval 3.14159 * 0.5
          num_leaders: 5
          num_followers: 40
        BoidSpawner:
          spawn_rule: Circle
          radius_fraction: !eval 1/5
          velocity_fraction: !eval 1/2
          fix_all: False
        BoidsColony:
          radius_repulsion: 2
          radius_orientation: 3
          radius_attraction: 5
          repulsion_multiplier: 3
          orientation_multiplier: 1
          attraction_multiplier: 1
          wall_avoidance_multiplier: 1
          dt: !eval 1/5
        POISpawner:
          poi_spawn_rule: BoundedCircle
          num_pois: 10
          bound_fraction: !eval 1/2
          inner_circle_bound_fraction: !eval 1/5
          outer_circle_bound_fraction: !eval 2/5
          fix_poi_spawns: False
        POIColony:
          observation_radius: 5
          coupling: 5
        ObservationManager:
          observation_rule: Individual
          num_poi_bins: 4
          num_swarm_bins: 12
          poi_sensor_type: InverseDistance
          swarm_sensor_type: InverseDistance
        Renderer:
          pixels_per_unit: 10
