CCEA:
  config:
    BoidsEnv:
      config:
        BoidSpawner:
          spawn_rule: Individual
          position_rule: Set
          velocity_rule: FixedStart
          heading_rule: FixedStart
          velocity_fraction: 0.0
          start_heading: !eval 3.14159
          leader_positions: # 4 leaders
            - [35, 45]
            - [35, 40]
            - [40, 40]
            - [45, 40]
          follower_positions: # 8 followers
            # First row
            - [37.5, 45]
            - [40, 45]
            - [42.5, 45]
            - [45, 45]
            # Second row
            - [37.5, 42.5]
            - [40, 42.5]
            - [42.5, 42.5]
            - [45, 42.5] 
        BoidsColony:
          dt: !eval 1/5
          radius_attraction: !eval 10
          radius_orientation: !eval 6
          radius_repulsion: !eval   4
          attraction_multiplier: 1
          orientation_multiplier: 1
          repulsion_multiplier: 1
          wall_avoidance_multiplier: 1
        ObservationManager:
          num_poi_bins: 4
          num_swarm_bins: 4
          observation_rule: Individual
          poi_sensor_type: Density
          swarm_sensor_type: Density
          observation_radius: ~
          full_observability: true
        POIColony:
          coupling: 3
          observation_radius: 0.1
        POISpawner:
          positions:
            # A
            - [5, 40]
            - [5, 40]
            # B
            - [10, 35]
            - [10, 35]
            - [10, 35]
            - [10, 35]
            # C
            - [5, 30]
            - [5, 30]
            - [5, 30]
            - [5, 30]
            # D
            - [2.5, 10]
            - [2.5, 10]
            - [2.5, 10]
            - [2.5, 10]
            - [2.5, 10]
            # E
            - [5, 7.5]
            # F
            - [12.5, 7.5]
            - [12.5, 7.5]
            # G
            - [15, 10]
            - [15, 10]
            - [15, 10]
            # H
            - [40, 10]
            - [40, 10]
            # I
            - [40, 15]
            # J
            - [40, 20]
          poi_spawn_rule: Set
        Renderer:
          leader_colors:
          - - 250
            - 120
            - 0
          - - 120
            - 0
            - 250
          - - 250
            - 250
            - 0
          - - 0
            - 200
            - 0
          - - 120
            - 0
            - 120
          - - 66
            - 245
            - 242
          pixels_per_unit: 10
        StateBounds:
          max_acceleration: 5
          max_angular_velocity: 1.570795
          max_velocity: 10
          min_velocity: 0
          num_followers: 8
          num_leaders: 4
        map_dimensions:
          x: 50
          y: 50
      init_seed: 1
      max_steps: !eval 5*20
      render_mode: none
  mutation_probability: 0.15
  mutation_rate: 0.1
  nn_hidden:
  - 10
  - 10
  num_evaluations: 1
  num_workers: 15
  sub_population_size: 30
  use_difference_evaluations: true
load_population: null
num_generations: 500
