---
num_generations: 5000
load_population: ~
CCEA:
  sub_population_size: 15
  num_parents: 5
  mutation_rate: 0.15
  mutation_probability: 0.15
  nn_hidden:
    - 14
    - 14
  num_workers: 8
  use_difference_evaluations: True
  num_evaluations: 1
  config:
    BoidsEnv:
      max_steps: !eval 10*3
      render_mode: none
      init_seed: 0
      config:
        map_dimensions:
          x: 50
          y: 50
        StateBounds:
          min_velocity: 0
          max_velocity: 20
          max_acceleration: 10
          max_angular_velocity: !eval 3.14159 * 0.5
          num_leaders: 3
          num_followers: 0
        BoidSpawner:
          spawn_rule: Circle
          radius_fraction: !eval 1/50
          velocity_fraction: !eval 0/1
          fix_all: True
        BoidsColony:
          radius_repulsion: 2
          radius_orientation: 3
          radius_attraction: 5
          repulsion_multiplier: 3
          orientation_multiplier: 1
          attraction_multiplier: 1
          wall_avoidance_multiplier: 1
          dt: !eval 1/3
        POISpawner:
          poi_spawn_rule: FixedConcentricCircles
          num_pois: ~
          bound_fraction: !eval 1/2
          inner_circle_bound_fraction: !eval 1/5
          outer_circle_bound_fraction: !eval 2/5
          fix_poi_spawns: False
          num_pois_concentric:
            - 13
          concentric_radii_fraction:
            - !eval 3/7
        POIColony:
          observation_radius: 5
          coupling: 1
        ObservationManager:
          observation_rule: Individual
          num_poi_bins: 4
          num_swarm_bins: 4
          poi_sensor_type: InverseDistance
          swarm_sensor_type: InverseDistance
        Renderer:
          pixels_per_unit: 20
          leader_colors:
            - [250, 120, 0]
            - [120, 0, 250]
            - [250,250,0]
            - [0,200,0]
            - [120,0,120]
            - [66,245,242]
