CCEA:
  config:
    BoidsEnv:
      config:
        BoidSpawner:
          spawn_rule: Individual
          position_rule: Set
          velocity_rule: FixedStart
          heading_rule: FixedStart
          velocity_fraction: 0.0
          start_heading: !eval 3.14159
          leader_positions: # 2 leaders
            - [85, 90]
            - [85, 75]
          follower_positions: # 2 followers
            - [85, 85]
            - [85, 80]
        BoidsColony:
          dt: !eval 1/5
          radius_attraction: !eval 10
          radius_orientation: !eval 6
          radius_repulsion: !eval   4
          attraction_multiplier: 2
          orientation_multiplier: 2
          repulsion_multiplier: 2
          wall_avoidance_multiplier: 1
        ObservationManager:
          num_poi_bins: 4
          num_swarm_bins: 4
          observation_rule: Individual
          poi_sensor_type: Density
          swarm_sensor_type: Density
          observation_radius: ~
          full_observability: true
        POIColony:
          coupling: 2
          observation_radius: 0.1
        FitnessCalculator:
          which_G: MinContinuous
          which_D: DFollow
        POISpawner:
          positions:
            - [10, 90]
            - [10, 10]
          poi_spawn_rule: Set
        Renderer:
          leader_colors:
          - - 250
            - 120
            - 0
          - - 120
            - 0
            - 250
          - - 250
            - 250
            - 0
          - - 0
            - 200
            - 0
          - - 120
            - 0
            - 120
          - - 66
            - 245
            - 242
          pixels_per_unit: 10
        StateBounds:
          max_acceleration: 5
          max_angular_velocity: 1.570795
          max_velocity: 10
          min_velocity: 0
          num_followers: 2
          num_leaders: 2
        map_dimensions:
          x: 100
          y: 100
      init_seed: 1
      max_steps: !eval 5*20
      render_mode: none
  mutation_probability: 0.15
  mutation_rate: 0.1
  nn_hidden:
  - 10
  - 10
  num_evaluations: 1
  num_workers: 1
  sub_population_size: 30
load_population: null
num_generations: 50
