leader_positions:
  - [25, 25]
follower_positions: []
poi_positions:
  - [ 27, 25 ]
  - [ 28, 25 ]
  - [ 29, 25 ]
  - [ 30, 25 ]
  - [ 31, 25 ]
  - [ 32, 25 ]
  - [ 33, 25 ]
  - [ 34, 25 ]
  - [ 35, 25 ]