spawn_rule: Individual
position_rule: Set
velocity_rule: FixedStart
heading_rule: FixedStart
velocity_fraction: 0.0
start_heading: !eval 3.14159/2
dt: !eval 1/5
radius_attraction: !eval 5
radius_orientation: !eval 1.000000001
radius_repulsion: !eval   1
attraction_multiplier: 5
orientation_multiplier: 0
repulsion_multiplier: 1
wall_avoidance_multiplier: 1
num_poi_bins: 4
num_swarm_bins: 4
observation_rule: Individual
poi_sensor_type: Density
swarm_sensor_type: Density
observation_radius: ~
full_observability: true
poi_coupling: 3
poi_observation_radius: 5
poi_spawn_rule: Set
pixels_per_unit: 20
max_acceleration: 5
max_angular_velocity: 1.570795
max_velocity: 10
min_velocity: 0
map_dimensions:
  x: 50
  y: 50
reward_type: difference_leader
init_seed: 1
max_steps: !eval 5*5
render_mode: none
mutation_probability: 0.15
mutation_rate: 0.1
nn_hidden:
  - 10
num_evaluations: 5
num_workers: 8
sub_population_size: 25
use_difference_rewards: true
load_population: null
num_generations: 20