dt: !eval 1/5
radius_attraction: !eval 5
radius_orientation: !eval 1.000000001
radius_repulsion: !eval   1
attraction_multiplier: 5
repulsion_multiplier: 1
sensor_resolution: 4
leader_observation_radius: 5
poi_coupling: 3
poi_observation_radius: 5
min_velocity: 0
max_velocity: 10
map_dimensions:
  x: 50
  y: 50
mutation_probability: 0.15
mutation_rate: 0.1
nn_hidden:
  - 10
num_evaluations: 5
sub_population_size: 25
reward_function: global
load_population: null
num_generations: 20
episode_length: 50