leader_positions:
  - [15, 10]
  - [15, 15]
  - [20, 10]
  - [20, 15]
follower_positions:
  - [14, 9]
  - [14, 11]
  - [16, 9]
  - [16, 11]
  #
  - [14, 14]
  - [14, 16]
  - [16, 14]
  - [16, 16]
  #
  - [19, 9]
  - [19, 11]
  - [21, 9]
  - [21, 11]
  #
  - [19, 14]
  - [19, 16]
  - [21, 14]
  - [21, 16]
poi_positions:
  - [1, 5]
  - [2, 6]
  - [4, 2]
  - [6, 4]
  - [12, 6]
  #
  - [5, 13]
  - [6, 14]
  - [12, 15]
  #
  - [24, 14]
  #
  - [30, 2]
  - [35, 3]
  - [31, 7]
  #
  - [31, 14]
  - [36, 20]
  - [33, 22]
