leader_positions:
  - [15, 10]
  - [15, 15]
  - [20, 10]
  - [20, 15]

  - [ 12.5, 10 ]
  - [ 12.5, 15 ]
  #
  - [ 15, 7.5 ]
  - [ 15, 12.5 ]
  - [ 15, 17.5 ]
  #
  - [ 17.5, 10 ]
  - [ 17.5, 15 ]
  #
  - [ 20, 7.5 ]
  - [ 20, 12.5 ]
  - [ 20, 17.5 ]
  #
  - [ 22.5, 10 ]
  - [ 22.5, 15 ]
follower_positions:
  []
poi_positions:
  - [1, 5]
  - [2, 6]
  - [4, 2]
  - [6, 4]
  - [12, 6]
  #
  - [5, 13]
  - [6, 14]
  - [12, 15]
  #
  - [24, 14]
  #
  - [30, 2]
  - [35, 3]
  - [31, 7]
  #
  - [31, 14]
  - [36, 20]
  - [33, 22]
